import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: "0" , padding : "0"}}>
        <div
          style={{
            width: "100%",
            backgroundColor: "lightblue",
            height: "100px",
            
          }}
        >
          <h2>navbar</h2>
        </div>
        {children}

        <div
          style={{
            width: "100%",
            backgroundColor: "lightblue",
            height: "100px",
          }}
        >
          <h2>footer</h2>
        </div>
      </body>
    </html>
  );
}
